export const data= [
  {
    id: 1,
    src: 'https://www.sessionlab.com/wp-content/uploads/One-hour-Brain-Sprint-cover.png',
    topic: 'WARP Remote Retrospective',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nulla qui iure eaque reiciendis laudantium hic ratione magnam blanditiis alias quasi.',
    objective: [
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Vitae, laboriosam?',
      ,
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Vitae, laboriosam?',
      ,
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Vitae, laboriosam?',
      ,
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Vitae, laboriosam?',
      ,
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Vitae, laboriosam?',
    ],
    src2: 'https://www.sessionlab.com/wp-content/uploads/Sabrina-Goerlich-profile.jpeg',
    name: 'Sabrina Goerlich',
    cred: 'Founder and Strategic Designer at Asenauer’s Designsprintstudio',
  },

  {
    id: 2,
    src: 'https://www.sessionlab.com/wp-content/uploads/Depositphotos_44590267_s-2019.jpg',
    topic: ' Remote problem solving workshop',
    desc: 'A problem-solving workshop designed from the ground up for remote teams and those working online. Facilitate a group through a collaborative problem-solving process remotely and generate quick, effective solutions!',
    objective: [
      'Identify what your current organizational challenges are.',
      'Generate ideas for effective, quick to implement solutions and choose which solutions to implement.',
    ],
    src2: 'https://www.sessionlab.com/wp-content/uploads/2018/01/logo_512_transparent.png',
    name: 'SessionLab',
    cred: 'SessionLab Templates',
  },
  {
    id: 3,
    src: 'https://www.sessionlab.com/wp-content/uploads/Marketing_sprint_canvas.jpeg',
    topic: 'Marketing Strategy Spirint',
    desc: 'The Marketing Strategy Spirint is a step-by-step process for clarifying campaign creation or entire marketing strategies in a single working day. It works well in both remote and live settings and is especially useful for aligning marketing teams and decision-makers. ',
    objective: [
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Vitae, laboriosam?',
      ,
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Vitae, laboriosam?',
    ],
    src2: 'https://www.sessionlab.com/wp-content/uploads/Karl-Filtness-thumbnail.jpeg',
    name: 'Karl Filtness',
    cred: 'Director of Growth, MEOM',
  },
  {
    id: 4,
    src: 'https://www.sessionlab.com/wp-content/uploads/Enterprise-Design.png',
    topic: ' Enterprise Design Starter Kit',
    desc: 'Enterprise Design is the design of ambitious endeavours. It is about bringing together all the elements needed to make an enterprise successfully deliver.',
    objective: [
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Vitae, laboriosam?',
    ],
    src2: 'https://www.sessionlab.com/wp-content/uploads/Milan-Guenther-profile-image.jpg',
    name: 'Milan Guenther',
    cred: 'Partner at Enterprise Design Associates',
  },
  {
    id: 5,
    src: 'https://www.sessionlab.com/wp-content/uploads/Emotional-Culture-Workshop-Cover-1500x1000.jpg',
    topic: ' Emotional Culture Workshop',
    desc: 'A compact and hands-on workshop to define the emotional culture of your team or organisation with the help of The Emotional Culture Deck.NUMBER OF PEOPLE: up to 30 people LENGTH: 2.5 hours',
    objective: [
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Vitae, laboriosam?',
      ,
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Vitae, laboriosam?',
      ,
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Vitae, laboriosam?',
      ,
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit.Vitae, laboriosam?',
    ],
    src2: 'https://www.sessionlab.com/wp-content/uploads/Jeremy-Dean.png',
    name: 'Jeremy Dean',
    cred: 'Founder of riders&elephants and creator of The Emotional Culture Deck',
  },
  {
    id: 6,
    src: 'https://www.sessionlab.com/wp-content/uploads/IMG_3993.jpeg',
    topic: ' Leadership development workshop (ideal for new leaders)',
    desc: 'Encourage an understanding of effective leadership values and an awareness of different leadership styles.This workshop is ideal for participants who are stepping into a leadership role for the first time.',
    objective: [],
    src2: 'https://www.sessionlab.com/wp-content/uploads/both-v4.jpg',
    name: 'Ute Nitschke & Nadja Petranovskaja',
    cred: 'Psychologists and facilitation experts',
  },
]

